# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  autoCancel: true
  drafts: true

pool: POOL1

steps:
- script: |
    python3 -m pip install tox --user
  displayName: 'install tox'

- script: |
    python3 -m tox
  displayName: 'Run toxt'

